services:

  backend_1:
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    logging:
      driver: json-file

  backend_2:
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    logging:
      driver: json-file

  worker:
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
    logging:
      driver: json-file

  postgres:
    deploy:
      resources:
        limits:
          memory: 512M

  redis:
    deploy:
      resources:
        limits:
          memory: 256M