server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        try_files $uri /index.html;
    }

    location /api/ {
        proxy_pass http://backend_upstream$request_uri;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/stats {
        proxy_pass http://backend_upstream$request_uri;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        # proxy_cache stats_cache;
        # proxy_cache_valid 200 30s;
        # add_header X-Cache-Status $upstream_cache_status;
    }
}

upstream backend_upstream {
    server backend_1:4000;
    server backend_2:4000;
}

proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=stats_cache:10m max_size=10m inactive=60m use_temp_path=off;